# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

before_install:
  - npm install
  - npm install mjml

warnings_are_errors: false
